name: Docker Image CI

on:
  push:
    branches: [ "algorithm" ]

jobs:

  Push the newly latest Image to Docker hub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fyp-algorithm:latest
    - name: Push Docker image
      run: |
          docker tag fyp-algorithm:latest jawwadhabib/fyp-algorithm:latest
          docker push jawwadhabib/fyp-algorithm:latest