name: Docker Image CI

on:
  push:
    branches: [ "backend" ]

jobs:

  push_latest_image_to_docker_hub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fyp-backend:latest
    - name: Push Docker image
      run: |
          docker tag fyp-backend:latest jawwadhabib/fyp-backend:latest
          docker push jawwadhabib/fyp-backend:latest